name: Deploy to GCP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key and ssh-agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_deploy_key
          ssh-keyscan -H ${{ secrets.GCP_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/github_deploy_key ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} "echo 'SSH Connection Successful'"

      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_deploy_key ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} << 'EOF'
            cd /home/softchocopie/Retriever_backend
            git pull origin develop
            screen -S api_server -X quit || true  # 기존 세션 종료 (없으면 무시)
            screen -dmS api_server bash -c "cd /home/softchocopie/Retriever_backend/Modules && source ../.venv/bin/activate && python3 app.py"
          EOF
